name: ContentBox LTS Flow

on:
  push:
    branches:
      - "releases/**"

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  ##########################################################################################
  # Format Source Code
  ##########################################################################################
  # format:
  #   name: Code Auto-Formatting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6

  #     # We use snapshot here due to the fixes in BoxLang for the formatter
  #     # Once v1.14.0 releases, we can switch to that version
  #     - name: Setup BoxLang
  #       uses: ortus-boxlang/setup-boxlang@main
  #       with:
  #         version: snapshot

  #     - name: Run Formatter
  #       run: boxlang format --source config,handlers,modules/contentbox,tests/specs

  #     - name: Commit Format Changes
  #       uses: stefanzweifel/git-auto-commit-action@v7
  #       with:
  #         commit_message: Apply cfformat changes
  #         push_options: --force
